# @package _group_
_target_: models.criterion.SetCriterion
num_classes: ${general.num_targets}
eos_coef: 0.1
losses:
  - "labels"
  - "masks"
  - "articulations"
num_points: ${matcher.num_points}
oversample_ratio: 3.0
importance_sample_ratio: 0.75
class_weights: -1
regular_arti_loss: True
use_mov_mask_for_interaction_loss: False